server:
  port: 8001
  servlet:
    context-path: /member

# 数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://117.72.38.128/train_member?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai

# mybatis xml路径
logging:
  level:
    com:
      jiawa:
        train:
          member:
            mapper: trace
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
